// Пресс-конференция: три вопроса подряд, на каждый — несколько секунд и три тона ответа.
// Вопросы подбираются под положение страны. Слоты: {crisis}, {pact}, {capital}.
// Ответы — прямая речь президента; эффекты небольшие, но складываются за три вопроса.
import type { PressQuestion } from "../game/types.ts";

export type PressWhen = "always" | "crisis" | "lowEcon" | "lowLegit" | "elect" | "pact" | "highMil" | "highRating" | "lowRep" | "betrayal" | "arc";
export const PRESS_QUESTIONS: (PressQuestion & { when: PressWhen })[] = [
  { id: "promises", when: "always", who: "Корреспондент оппозиционного канала", topic: "невыполненных обещаниях",
    text: "Ваши оппоненты говорят, что вы обещали больше, чем сделали. Что вы им ответите?",
    answers: [
      { tone: "honest", text: "«В одном они правы: сделано не всё. Вот список того, что не успели, и сроки»", res: { internalLegitimacy: 3, politicalCapital: -2 }, rel: { liberal: 3 } },
      { tone: "hard", text: "«Они двадцать лет обещали и не сделали ничего. Я за полгода сделал больше»", res: { politicalCapital: 3, externalReputation: -1 }, rel: { nationalist: 3, liberal: -3 } },
      { tone: "evasive", text: "«Давайте дождёмся итогов года — тогда и поговорим»", res: { internalLegitimacy: -1 }, rel: {} },
    ] },
  { id: "crisis", when: "crisis", who: "Корреспондентка информационного агентства", topic: "кризисе",
    text: "Кризис «{crisis}» длится не первую неделю. Когда это закончится?",
    answers: [
      { tone: "honest", text: "«Не скоро. Врать не буду: ещё месяц будет трудно»", res: { internalLegitimacy: 3, politicalCapital: -1 }, rel: {} },
      { tone: "hard", text: "«Это закончится, когда виновные ответят. Списки уже готовят»", res: { politicalCapital: 2, externalReputation: -2 }, rel: { security: 3, liberal: -3 } },
      { tone: "evasive", text: "«Ситуация под контролем»", res: { internalLegitimacy: -2 }, rel: {} },
    ] },
  { id: "prices", when: "lowEcon", who: "Журналист деловой газеты", topic: "ценах",
    text: "Цены растут, зарплаты — нет. Что вы скажете людям, которым нечем платить по счетам?",
    answers: [
      { tone: "honest", text: "«Что это моя ответственность. И что тарифы заморожены с понедельника»", res: { internalLegitimacy: 3, economy: -2 }, rel: { regional: 2 } },
      { tone: "hard", text: "«Что зарплаты не растут там, где не работают. Работы в стране достаточно»", res: { politicalCapital: 1, internalLegitimacy: -3 }, rel: { business: 3, regional: -3 } },
      { tone: "evasive", text: "«Правительство готовит комплекс мер»", res: { internalLegitimacy: -1 }, rel: {} },
    ] },
  { id: "leaks", when: "always", who: "Корреспондент вечерних новостей", topic: "утечках",
    text: "Говорят, в вашем окружении есть люди, которые сливают информацию. Это правда?",
    answers: [
      { tone: "honest", text: "«Утечки есть. Мы их ищем — и найдём»", res: { internalLegitimacy: 2, politicalCapital: -1 }, rel: {} },
      { tone: "hard", text: "«Слухи распускают те, кому выгоден хаос. Их мы тоже найдём»", res: { politicalCapital: 2, externalReputation: -1 }, rel: { security: 2, liberal: -3 } },
      { tone: "evasive", text: "«Слухи я не комментирую»", res: { internalLegitimacy: -1 }, rel: {} },
    ] },
  { id: "course", when: "always", who: "Иностранный корреспондент", topic: "внешнем курсе",
    text: "Так куда вы ведёте страну — на Запад или к Москве?",
    answers: [
      { tone: "honest", text: "«К собственной стране. Остальное — география»", res: { internalLegitimacy: 2, externalReputation: 1 }, rel: { nationalist: 2 } },
      { tone: "hard", text: "«В Европу. Это выбор наших людей, и он окончательный»", res: { externalReputation: 3 }, rel: { west: 5, russia: -5 } },
      { tone: "evasive", text: "«Мы ценим добрые отношения со всеми соседями»", res: { externalReputation: -1 }, rel: {} },
    ] },
  { id: "square", when: "lowLegit", who: "Корреспондентка независимого издания", topic: "людях на площади",
    text: "На площади снова люди. Вы выйдете к ним?",
    answers: [
      { tone: "honest", text: "«Выйду. Сегодня же вечером, без охраны»", res: { internalLegitimacy: 4, politicalCapital: -2 }, rel: { liberal: 4, security: -3 } },
      { tone: "hard", text: "«Те, кто стоит на площади, не представляют страну»", res: { politicalCapital: 2, internalLegitimacy: -3 }, rel: { security: 3, liberal: -5 } },
      { tone: "evasive", text: "«Мой кабинет открыт для всех»", res: { internalLegitimacy: -1 }, rel: {} },
    ] },
  { id: "election", when: "elect", who: "Политический обозреватель", topic: "выборах",
    text: "До выборов считанные дни. Вы уверены в победе?",
    answers: [
      { tone: "honest", text: "«Уверен только в одном: буду работать до последнего дня»", res: { internalLegitimacy: 2 }, rel: {} },
      { tone: "hard", text: "«Да. Альтернативы нет, и люди это знают»", res: { politicalCapital: 2, internalLegitimacy: -2 }, rel: { liberal: -3, ruling: 2 } },
      { tone: "evasive", text: "«Пусть решают избиратели»", res: { internalLegitimacy: 1, politicalCapital: -1 }, rel: {} },
    ] },
  { id: "pact", when: "pact", who: "Корреспондент парламентской газеты", topic: "договоре",
    text: "У вас договор с лагерем «{pact}». Не боитесь, что вас сочтут их марионеткой?",
    answers: [
      { tone: "honest", text: "«Договор — это не дружба, а расчёт. И я его соблюдаю»", res: { politicalCapital: 2 }, rel: {} },
      { tone: "hard", text: "«Если договор перестанет работать на страну — я его разорву»", res: { internalLegitimacy: 2, politicalCapital: -1 }, rel: {} },
      { tone: "evasive", text: "«Наши партнёры — все граждане страны»", res: {}, rel: {} },
    ] },
  { id: "regions", when: "always", who: "Корреспондентка регионального радио", topic: "провинции",
    text: "В провинции говорят, что столица о них забыла. Когда вы к ним приедете?",
    answers: [
      { tone: "honest", text: "«На следующей неделе. Без кортежа и без предупреждения»", res: { internalLegitimacy: 2, personalResource: -2 }, rel: { regional: 4 } },
      { tone: "hard", text: "«Регионы получают больше, чем когда-либо. Цифры опубликованы»", res: { politicalCapital: 1 }, rel: { regional: -2 } },
      { tone: "evasive", text: "«Подробности даст профильный министр»", res: { internalLegitimacy: -1 }, rel: {} },
    ] },
  { id: "family", when: "always", who: "Журналист-расследователь", topic: "госконтрактах вашей семьи",
    text: "Правда ли, что фирмы ваших родственников получили госконтракты?",
    answers: [
      { tone: "honest", text: "«Нет. Вот моя декларация — проверяйте каждую строку»", res: { internalLegitimacy: 3, personalResource: -2 }, rel: { liberal: 2 } },
      { tone: "hard", text: "«Этот вопрос вам написали мои оппоненты»", res: { politicalCapital: 1, internalLegitimacy: -2, externalReputation: -1 }, rel: {} },
      { tone: "evasive", text: "«Без комментариев»", res: { internalLegitimacy: -3 }, rel: {} },
    ] },
  { id: "army", when: "highMil", who: "Корреспондентка общественного телевидения", topic: "военном бюджете",
    text: "Армия получила больше денег, чем школы. Это и есть ваши приоритеты?",
    answers: [
      { tone: "hard", text: "«Безопасность прежде всего. Без неё не будет и школ»", res: { military: 1 }, rel: { security: 4, liberal: -3 } },
      { tone: "honest", text: "«Нет. В следующем бюджете будет иначе — запишите»", res: { internalLegitimacy: 2 }, rel: { security: -4, liberal: 3 } },
      { tone: "evasive", text: "«Бюджет принимает парламент»", res: { politicalCapital: -1 }, rel: {} },
    ] },
  { id: "media", when: "always", who: "Представитель союза журналистов", topic: "свободе прессы",
    text: "Вчера закрыли ещё один телеканал. Это ваше решение?",
    answers: [
      { tone: "honest", text: "«Нет. И я прошу прокуратуру разобраться до конца недели»", res: { externalReputation: 2, internalLegitimacy: 1 }, rel: { liberal: 4, security: -2 } },
      { tone: "hard", text: "«Канал работал на иностранные деньги. Вопрос закрыт»", res: { politicalCapital: 2, externalReputation: -3 }, rel: { liberal: -5, nationalist: 2 } },
      { tone: "evasive", text: "«Это решение суда, а не президента»", res: { externalReputation: -1 }, rel: {} },
    ] },
  { id: "cabinet", when: "always", who: "Обозреватель правительственной газеты", topic: "правительстве",
    text: "Вы довольны своим правительством?",
    answers: [
      { tone: "honest", text: "«Не всеми. Кадровые решения будут скоро»", res: { internalLegitimacy: 2, politicalCapital: -1 }, rel: { ruling: -3 } },
      { tone: "hard", text: "«Это лучшая команда за двадцать лет»", res: { politicalCapital: 2, internalLegitimacy: -1 }, rel: { ruling: 3 } },
      { tone: "evasive", text: "«Оценки ставят избиратели»", res: {}, rel: {} },
    ] },
  { id: "free", when: "always", who: "Ведущая утреннего шоу", topic: "свободном времени",
    text: "Последний вопрос, полегче: что вы делаете в свободное время?",
    answers: [
      { tone: "honest", text: "«Читаю доклады. Иногда — между строк»", res: { personalResource: 2 }, rel: {} },
      { tone: "hard", text: "«У президента нет свободного времени»", res: { politicalCapital: 1 }, rel: {} },
      { tone: "evasive", text: "«Обещаю внукам приехать на выходные — и обычно не приезжаю»", res: { internalLegitimacy: 2 }, rel: {} },
    ] },
  { id: "plot", when: "arc", who: "Корреспондент оппозиционной газеты", topic: "слухах о заговоре",
    text: "Говорят, в вашем окружении зреет заговор. Что вам об этом известно?",
    answers: [
      { tone: "honest", text: "«Известно больше, чем мне хотелось бы. Подробности — когда будут доказательства»", res: { internalLegitimacy: 2, politicalCapital: -1 }, rel: {} },
      { tone: "hard", text: "«Тем, кто его затевает, советую подумать о последствиях. Они знают, о ком я»", res: { politicalCapital: 2, externalReputation: -1 }, rel: { security: 3 } },
      { tone: "evasive", text: "«Заговоры — это для сериалов»", res: { internalLegitimacy: -1 }, rel: {} },
    ] },
  { id: "betrayal", when: "betrayal", who: "Политический обозреватель", topic: "нарушенном договоре",
    text: "Вы нарушили договор с партнёрами. Почему с вами вообще кто-то должен договариваться?",
    answers: [
      { tone: "honest", text: "«Это была ошибка, и я за неё отвечаю. Следующий договор я выполню до последней строчки»", res: { internalLegitimacy: 2, politicalCapital: -2 }, rel: { ruling: 2 } },
      { tone: "hard", text: "«Договор перестал работать на страну. Я выбираю страну»", res: { politicalCapital: 2, externalReputation: -2 }, rel: { nationalist: 3 } },
      { tone: "evasive", text: "«У каждой стороны своя версия событий»", res: { internalLegitimacy: -2 }, rel: {} },
    ] },
  { id: "dictator", when: "lowRep", who: "Корреспондент иностранного агентства", topic: "репутации за рубежом",
    text: "Западные газеты называют вас «последним диктатором региона». Вам обидно?",
    answers: [
      { tone: "honest", text: "«Обидно. Значит, мы плохо объясняем, что делаем. Будем объяснять лучше»", res: { externalReputation: 3, politicalCapital: -1 }, rel: { west: 3 } },
      { tone: "hard", text: "«Пусть пишут. Мои избиратели живут здесь, а не в редакциях»", res: { politicalCapital: 2, externalReputation: -3 }, rel: { nationalist: 3, west: -4 } },
      { tone: "evasive", text: "«Я не читаю иностранную прессу»", res: { externalReputation: -1 }, rel: {} },
    ] },
  { id: "rating", when: "highRating", who: "Ведущий вечернего ток-шоу", topic: "высоком рейтинге",
    text: "Ваш рейтинг выше, чем у любого предшественника. Не боитесь, что это ненадолго?",
    answers: [
      { tone: "honest", text: "«Боюсь. Поэтому работаю так, будто он завтра упадёт»", res: { internalLegitimacy: 2 }, rel: {} },
      { tone: "hard", text: "«Рейтинг — это не удача, а результат. Результат будет и дальше»", res: { politicalCapital: 2, internalLegitimacy: -1 }, rel: { ruling: 2 } },
      { tone: "evasive", text: "«Я не слежу за рейтингами»", res: {}, rel: {} },
    ] },
  { id: "pension", when: "always", who: "Корреспондентка социального канала", topic: "пенсионном возрасте",
    text: "Будете повышать пенсионный возраст? Ответьте «да» или «нет».",
    answers: [
      { tone: "honest", text: "«Нет — пока я президент. И да, бюджету от этого тяжело»", res: { internalLegitimacy: 3, economy: -2 }, rel: { regional: 3, business: -2 } },
      { tone: "hard", text: "«Да. Иначе через десять лет платить будет нечем»", res: { economy: 3, internalLegitimacy: -4 }, rel: { business: 3, regional: -4 } },
      { tone: "evasive", text: "«Этот вопрос требует широкого обсуждения»", res: { internalLegitimacy: -2 }, rel: {} },
    ] },
  { id: "bureaucrats", when: "always", who: "Журналист экономического издания", topic: "сокращении чиновников",
    text: "Вы обещали сократить чиновников вдвое. Сколько уже сократили?",
    answers: [
      { tone: "honest", text: "«Пока — каждого десятого. Это мало, и я это знаю»", res: { internalLegitimacy: 2, politicalCapital: -1 }, rel: { ruling: -2 } },
      { tone: "hard", text: "«Достаточно, чтобы аппарат меня возненавидел. Значит, всё правильно»", res: { politicalCapital: 1, internalLegitimacy: 1 }, rel: { ruling: -4, liberal: 2 } },
      { tone: "evasive", text: "«Цифры вам предоставит администрация»", res: { internalLegitimacy: -1 }, rel: {} },
    ] },
  { id: "emigrants", when: "always", who: "Корреспондентка радио диаспоры", topic: "уехавших",
    text: "Что вы скажете семьям тех, кто уехал из страны за последний год?",
    answers: [
      { tone: "honest", text: "«Что мы их ждём. И что я сделаю всё, чтобы им было куда вернуться»", res: { internalLegitimacy: 2, externalReputation: 1 }, rel: { liberal: 3 } },
      { tone: "hard", text: "«Кто уехал в трудный час, сделал свой выбор»", res: { politicalCapital: 1, externalReputation: -2 }, rel: { nationalist: 3, liberal: -4 } },
      { tone: "evasive", text: "«Люди ездят — это нормально»", res: { internalLegitimacy: -1 }, rel: {} },
    ] },
  { id: "papers", when: "always", who: "Главный редактор сатирического журнала", topic: "газетах",
    text: "Правда ли, что вы не читаете газет?",
    answers: [
      { tone: "honest", text: "«Читаю. Особенно те, где меня ругают — там больше полезного»", res: { internalLegitimacy: 2, externalReputation: 1 }, rel: { liberal: 2 } },
      { tone: "hard", text: "«У меня есть доклады. Они точнее газет»", res: { politicalCapital: 1, internalLegitimacy: -1 }, rel: {} },
      { tone: "evasive", text: "«Иногда читаю ваш журнал. Смешно»", res: { personalResource: 1 }, rel: {} },
    ] },
  { id: "concert", when: "always", who: "Корреспондент культурного обозрения", topic: "запрете концерта",
    text: "{faith:Church} просит запретить концерт иностранной группы. Ваша позиция?",
    answers: [
      { tone: "honest", text: "«Концерт будет. Нравится — идите, не нравится — не ходите»", res: { externalReputation: 2 }, rel: { liberal: 3, church: -4 } },
      { tone: "hard", text: "«Есть вещи, которые наша страна не обязана терпеть»", res: { politicalCapital: 1, externalReputation: -2 }, rel: { church: 4, liberal: -3 } },
      { tone: "evasive", text: "«Пусть решают организаторы и город»", res: {}, rel: {} },
    ] },
  { id: "currency", when: "lowEcon", who: "Финансовый обозреватель", topic: "курсе валюты",
    text: "Курс бьёт рекорды. Вы сами храните сбережения в нашей валюте?",
    answers: [
      { tone: "honest", text: "«Да, все до копейки. Если ей не верю я, почему должны верить вы?»", res: { internalLegitimacy: 3, personalResource: -2 }, rel: {} },
      { tone: "hard", text: "«Курс раскачивают спекулянты. Ими займутся»", res: { politicalCapital: 1, economy: -1 }, rel: { security: 2, business: -3 } },
      { tone: "evasive", text: "«Мои сбережения — моё личное дело»", res: { internalLegitimacy: -3 }, rel: {} },
    ] },
  { id: "blame", when: "crisis", who: "Корреспондентка утренних новостей", topic: "виновных в кризисе",
    text: "Кто персонально ответит за кризис «{crisis}»?",
    answers: [
      { tone: "honest", text: "«Я. Остальные — после меня»", res: { internalLegitimacy: 3, personalResource: -2 }, rel: {} },
      { tone: "hard", text: "«Список фамилий уже у прокурора»", res: { politicalCapital: 2, internalLegitimacy: 1 }, rel: { ruling: -3, security: 2 } },
      { tone: "evasive", text: "«Сейчас не время искать виноватых»", res: { internalLegitimacy: -2 }, rel: {} },
    ] },
  { id: "memoirs", when: "always", who: "Литературный обозреватель", topic: "мемуарах бывшего советника",
    text: "Ваш бывший советник пишет мемуары. Вы их прочтёте?",
    answers: [
      { tone: "honest", text: "«Обязательно. Хочу узнать, что я тогда думал»", res: { internalLegitimacy: 1, personalResource: 1 }, rel: {} },
      { tone: "hard", text: "«Пусть пишет. Юристы прочтут первыми»", res: { politicalCapital: 1, externalReputation: -1 }, rel: {} },
      { tone: "evasive", text: "«У меня нет времени на художественную литературу»", res: { personalResource: 1 }, rel: {} },
    ] },
];

export const PRESS_TEXT = {
  title: ["Пресс-конференция накануне выборов", "Последняя пресс-конференция перед выборами"],
  // Если выборов в конце срока не будет — ушёл сам, отложил или отменил.
  titleNoVote: { exit: "Прощальная пресс-конференция", postpone: "Пресс-конференция в дни чрезвычайного положения", dictatorship: "Пресс-конференция без выборов на горизонте", none: "Пресс-конференция в резиденции" } as Record<string, string>,
  intro: "Большой зал, сто двадцать аккредитованных журналистов и три микрофона в проходах. Пресс-секретарь шепчет на ухо: «На каждый ответ — секунды. Любая пауза станет заголовком».",
  open: "Пресс-конференция длится сорок минут.",
  answer: "На вопрос {about} вы отвечаете: {text}.",
  silent: "На вопрос {about} вы молчите слишком долго — пауза становится главным кадром вечера.",
  close: {
    honest: ["Зал провожает вас аплодисментами — редкими, но настоящими. Вечером ваши ответы пересказывают дословно.",
      "После последнего ответа в зале на секунду тихо, а потом кто-то в заднем ряду говорит вслух: «Ну наконец-то». Эту фразу назавтра цитируют чаще ваших."],
    hard: ["Половина зала аплодирует, половина пишет гневные колонки. Зато никто не скажет, что президент мямлил.",
      "Вы уходите со сцены под стук клавиатур. К вечеру у вас вдвое больше сторонников и втрое больше врагов — и все они цитируют одно и то же."],
    evasive: ["Журналисты уходят с пустыми блокнотами — и именно это становится главной новостью вечера.",
      "Сорок минут слов — и ни одной цитаты, которую можно поставить в заголовок. Редакторы ставят в заголовок именно это."],
    mixed: ["Зал так и не понимает, какого президента видел сегодня — откровенного, жёсткого или осторожного. Вечерние колонки спорят друг с другом.",
      "Каждое издание выбирает свой ответ и строит на нём свою версию пресс-конференции. Читая их подряд, можно подумать, что выступали три разных человека."],
  },
  skip: {
    text: "Отменить пресс-конференцию",
    hint: "Ни одного неудобного вопроса — и ни одного ответа",
    scene: "Пресс-конференцию отменяют за час до начала «из-за плотного графика». Сто двадцать журналистов расходятся, и каждый пишет одно и то же: президент испугался вопросов.",
    head: "Президент отменил пресс-конференцию",
  },
};
